GPUassert: invalid device function src/base_neuron.cu 229
GPUassert: invalid device function src/base_neuron.cu 229
Traceback (most recent call last):
  File "/home/y-terans/workspace/nest-gpu/develop/brunel_mpi_without_remote.py", line 42, in <module>
    pg = ngpu.Create("poisson_generator")
  File "/usr/local/nestgpu/lib/python3.9/site-packages/nestgpu.py", line 214, in Create
Traceback (most recent call last):
  File "/home/y-terans/workspace/nest-gpu/develop/brunel_mpi_without_remote.py", line 42, in <module>
    pg = ngpu.Create("poisson_generator")
  File "/usr/local/nestgpu/lib/python3.9/site-packages/nestgpu.py", line 214, in Create
    raise ValueError(GetErrorMessage())
ValueError: b'CUDA error'
GPUassert: invalid device function src/base_neuron.cu 229
    raise ValueError(GetErrorMessage())
ValueError: b'CUDA error'
GPUassert: invalid device function src/base_neuron.cu 229
Traceback (most recent call last):
  File "/home/y-terans/workspace/nest-gpu/develop/brunel_mpi_without_remote.py", line 42, in <module>
    pg = ngpu.Create("poisson_generator")
  File "/usr/local/nestgpu/lib/python3.9/site-packages/nestgpu.py", line 214, in Create
Traceback (most recent call last):
  File "/home/y-terans/workspace/nest-gpu/develop/brunel_mpi_without_remote.py", line 42, in <module>
    raise ValueError(GetErrorMessage())
ValueError: b'CUDA error'
    pg = ngpu.Create("poisson_generator")
  File "/usr/local/nestgpu/lib/python3.9/site-packages/nestgpu.py", line 214, in Create
    raise ValueError(GetErrorMessage())
ValueError: b'CUDA error'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[51570,1],2]
  Exit code:    1
--------------------------------------------------------------------------
