terminate called after throwing an instance of 'ngpu_exception'
  what():  CUDA error
[c1:25913] *** Process received signal ***
[c1:25913] Signal: Aborted (6)
[c1:25913] Signal code:  (-6)
terminate called after throwing an instance of 'ngpu_exception'
  what():  CUDA error
[c1:25914] *** Process received signal ***
[c1:25914] Signal: Aborted (6)
[c1:25914] Signal code:  (-6)
[c1:25914] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f7d479aa520]
[c1:25914] [ 1] /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7f7d479fea7c]
[c1:25914] [ 2] /lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7f7d479aa476]
[c1:25914] [ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7f7d479907f3]
[c1:25914] [ 4] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa2bfe)[0x7f7d3c347bfe]
[c1:25914] [ 5] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae28c)[0x7f7d3c35328c]
[c1:25914] [ 6] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae2f7)[0x7f7d3c3532f7]
[c1:25914] [ 7] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae558)[0x7f7d3c353558]
[c1:25914] [ 8] /opt/nestgpu/lib/libnestgpu.so(+0x39599)[0x7f7d25e0c599]
[c1:25914] [ 9] /opt/nestgpu/lib/libnestgpu.so(checkNESTGPUInstance+0x2c)[0x7f7d25e7cb5c]
[c1:25914] [10] /opt/nestgpu/lib/libnestgpu.so(NESTGPU_SetOnException+0xc)[0x7f7d25e7cbcc]
[c1:25914] [11] /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e)[0x7f7d46e74e2e]
[c1:25914] [12] /lib/x86_64-linux-gnu/libffi.so.8(+0x4493)[0x7f7d46e71493]
[c1:25914] [13] /opt/pyenv/versions/3.10.7/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x12e05)[0x7f7d44cc7e05]
[c1:25914] [14] /opt/pyenv/versions/3.10.7/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0xc8d0)[0x7f7d44cc18d0]
[c1:25914] [15] /opt/pyenv/versions/3.10.7/bin/python(_PyObject_MakeTpCall+0x8c)[0x55620a7fa81c]
[c1:25914] [16] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x7bb1)[0x55620a7ea461]
[c1:25914] [17] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x55620a8a4bb4]
[c1:25914] [18] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x67ce)[0x55620a7e907e]
[c1:25914] [19] /opt/pyenv/versions/3.10.7/bin/python(PyEval_EvalCode+0xd0)[0x55620a8a49e0]
[c1:25914] [20] /opt/pyenv/versions/3.10.7/bin/python(+0x2474cd)[0x55620a9ce4cd]
[c1:25914] [21] /opt/pyenv/versions/3.10.7/bin/python(+0x21ae23)[0x55620a9a1e23]
[c1:25914] [22] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x176e)[0x55620a7e401e]
[c1:25914] [23] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x55620a8a4bb4]
[c1:25914] [24] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x94dd)[0x55620a7ebd8d]
[c1:25914] [25] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x55620a8a4bb4]
[c1:25914] [26] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x61b1)[0x55620a7e8a61]
[c1:25914] [27] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x55620a8a4bb4]
[c1:25914] [28] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x67ce)[0x55620a7e907e]
[c1:25914] [29] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x55620a8a4bb4]
[c1:25914] *** End of error message ***
[c1:25913] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fc6fa31d520]
[c1:25913] [ 1] /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7fc6fa371a7c]
[c1:25913] [ 2] /lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7fc6fa31d476]
[c1:25913] [ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7fc6fa3037f3]
[c1:25913] [ 4] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa2bfe)[0x7fc6eecb5bfe]
[c1:25913] [ 5] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae28c)[0x7fc6eecc128c]
[c1:25913] [ 6] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae2f7)[0x7fc6eecc12f7]
[c1:25913] [ 7] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae558)[0x7fc6eecc1558]
[c1:25913] [ 8] /opt/nestgpu/lib/libnestgpu.so(+0x39599)[0x7fc6dc600599]
[c1:25913] [ 9] /opt/nestgpu/lib/libnestgpu.so(checkNESTGPUInstance+0x2c)[0x7fc6dc670b5c]
[c1:25913] [10] /opt/nestgpu/lib/libnestgpu.so(NESTGPU_SetOnException+0xc)[0x7fc6dc670bcc]
[c1:25913] [11] /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e)[0x7fc6f989ce2e]
[c1:25913] [12] /lib/x86_64-linux-gnu/libffi.so.8(+0x4493)[0x7fc6f9899493]
[c1:25913] [13] /opt/pyenv/versions/3.10.7/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x12e05)[0x7fc6f98b4e05]
[c1:25913] [14] /opt/pyenv/versions/3.10.7/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0xc8d0)[0x7fc6f98ae8d0]
[c1:25913] [15] /opt/pyenv/versions/3.10.7/bin/python(_PyObject_MakeTpCall+0x8c)[0x5563c521381c]
[c1:25913] [16] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x7bb1)[0x5563c5203461]
[c1:25913] [17] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x5563c52bdbb4]
[c1:25913] [18] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x67ce)[0x5563c520207e]
[c1:25913] [19] /opt/pyenv/versions/3.10.7/bin/python(PyEval_EvalCode+0xd0)[0x5563c52bd9e0]
[c1:25913] [20] /opt/pyenv/versions/3.10.7/bin/python(+0x2474cd)[0x5563c53e74cd]
[c1:25913] [21] /opt/pyenv/versions/3.10.7/bin/python(+0x21ae23)[0x5563c53bae23]
[c1:25913] [22] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x176e)[0x5563c51fd01e]
[c1:25913] [23] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x5563c52bdbb4]
[c1:25913] [24] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x94dd)[0x5563c5204d8d]
[c1:25913] [25] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x5563c52bdbb4]
[c1:25913] [26] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x61b1)[0x5563c5201a61]
[c1:25913] [27] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x5563c52bdbb4]
[c1:25913] [28] /opt/pyenv/versions/3.10.7/bin/python(_PyEval_EvalFrameDefault+0x67ce)[0x5563c520207e]
[c1:25913] [29] /opt/pyenv/versions/3.10.7/bin/python(+0x11dbb4)[0x5563c52bdbb4]
[c1:25913] *** End of error message ***
SIGABRT: abort
PC=0x47cdab m=0 sigcode=0

goroutine 1 [running, locked to thread]:
syscall.RawSyscall(0x3e, 0x64ea, 0x6, 0x0, 0x0, 0xc000024060, 0xc000024060)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc00018de70 sp=0xc00018de68 pc=0x47cdab
syscall.Kill(0x64ea, 0x6, 0x0, 0x0)
	/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc00018deb8 sp=0xc00018de70 pc=0x479bcb
github.com/sylabs/singularity/internal/app/starter.Master.func2()
	internal/app/starter/master_linux.go:152 +0x61 fp=0xc00018df00 sp=0xc00018deb8 pc=0x7928f1
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
	internal/pkg/util/mainthread/mainthread.go:21 +0x2f fp=0xc00018df28 sp=0xc00018df00 pc=0x790f4f
main.main()
	cmd/starter/main_linux.go:102 +0x5f fp=0xc00018df60 sp=0xc00018df28 pc=0x972bbf
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:203 +0x21e fp=0xc00018dfe0 sp=0xc00018df60 pc=0x433b4e
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00018dfe8 sp=0xc00018dfe0 pc=0x45f7c1

goroutine 6 [syscall]:
os/signal.signal_recv(0xb9da80)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc0002b9ba0)
	internal/pkg/util/mainthread/mainthread.go:24 +0xb4
github.com/sylabs/singularity/internal/app/starter.Master(0x7, 0x5, 0x6539, 0xc00000f200)
	internal/app/starter/master_linux.go:151 +0x44c
main.startup()
	cmd/starter/main_linux.go:75 +0x53e
created by main.main
	cmd/starter/main_linux.go:98 +0x35

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x64ea
rsi    0x6
rbp    0xc00018dea8
rsp    0xc00018de68
r8     0x0
r9     0x0
r10    0x0
r11    0x202
r12    0xf3
r13    0x0
r14    0xb83e88
r15    0x0
rip    0x47cdab
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
SIGABRT: abort
PC=0x47cdab m=0 sigcode=0

goroutine 1 [running, locked to thread]:
syscall.RawSyscall(0x3e, 0x64e8, 0x6, 0x0, 0x0, 0xc000024060, 0xc000024060)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc0001abe70 sp=0xc0001abe68 pc=0x47cdab
syscall.Kill(0x64e8, 0x6, 0x0, 0x0)
	/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc0001abeb8 sp=0xc0001abe70 pc=0x479bcb
github.com/sylabs/singularity/internal/app/starter.Master.func2()
	internal/app/starter/master_linux.go:152 +0x61 fp=0xc0001abf00 sp=0xc0001abeb8 pc=0x7928f1
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
	internal/pkg/util/mainthread/mainthread.go:21 +0x2f fp=0xc0001abf28 sp=0xc0001abf00 pc=0x790f4f
main.main()
	cmd/starter/main_linux.go:102 +0x5f fp=0xc0001abf60 sp=0xc0001abf28 pc=0x972bbf
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:203 +0x21e fp=0xc0001abfe0 sp=0xc0001abf60 pc=0x433b4e
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001abfe8 sp=0xc0001abfe0 pc=0x45f7c1

goroutine 19 [syscall]:
os/signal.signal_recv(0xb9da80)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

goroutine 5 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc0002dbbc0)
	internal/pkg/util/mainthread/mainthread.go:24 +0xb4
github.com/sylabs/singularity/internal/app/starter.Master(0x7, 0x5, 0x653a, 0xc00000e840)
	internal/app/starter/master_linux.go:151 +0x44c
main.startup()
	cmd/starter/main_linux.go:75 +0x53e
created by main.main
	cmd/starter/main_linux.go:98 +0x35

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x64e8
rsi    0x6
rbp    0xc0001abea8
rsp    0xc0001abe68
r8     0x0
r9     0x0
r10    0x0
r11    0x202
r12    0xf3
r13    0x0
r14    0xb83e88
r15    0x0
rip    0x47cdab
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[22533,1],1]
  Exit code:    2
--------------------------------------------------------------------------
